name: Lint PR

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - staging

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # we need + 1 commit
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint pull request commit message when it has a single commit
        if: ${{ github.event.pull_request.commits == '1' }}
        run: |
          echo "Since your PR has a single commit, this commit should adhere to the commit message convention."
          echo "Please amend your commit message (git commit --amend) if commitlint reports an error and push using: git push --force-with-lease"
          echo "$(git show -s --format=%B HEAD^2)" | npx commitlint --verbose --help-url https://github.com/dialpad/dialtone/blob/staging/.github/COMMIT_CONVENTION.md --verbose

      - name: Lint pull request title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose

      - name: Lint less
        run: npm run lint
