name: Deploy

on:
  push:
    branches:
      - production
      - alpha
      - beta
      - 'DT-424-ci-deploy-website-independently-of-library'
    paths:
      - 'lib/**'

jobs:
  deploy:
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: parse branch from ref
        id: branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}

      # Will prevent the rest of the steps from running on fail
      - name: Check if user is a dialpad member
        uses: octokit/request-action@v2.1.0
        with:
          route: GET /orgs/dialpad/members/${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.DIALTONE_CI_TOKEN }}

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.DIALTONE_NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      # note that npm run build is executed before publishing via prepublishOnly
      - name: Deploy production
        run: npm publish --dry-run

      - name: Deploy prerelease
        run: npm publish --dry-run --tag ${{ steps.branch.outputs.BRANCH }}

      - name: Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends ./release-ci.config.js
